# Generated by Django 2.2.5 on 2019-10-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191001_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='enlace',
            field=models.CharField(max_length=100),
        ),
    ]
