# Generated by Django 2.2.5 on 2019-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_entrada_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(upload_to='blog/static/img/archivo/'),
        ),
    ]
