# Generated by Django 2.2.5 on 2019-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
