# Generated by Django 2.2.5 on 2019-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191002_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
    ]
