# Generated by Django 2.2.5 on 2019-10-02 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_catalogo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogo',
            new_name='Serie',
        ),
    ]
