# Generated by Django 2.2.5 on 2019-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191002_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='enlace',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='archivo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='informacion',
            field=models.TextField(blank=True),
        ),
    ]
