# Generated by Django 2.2.5 on 2019-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191008_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='serie',
            name='capturaCuatro',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='serie',
            name='capturaDos',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='serie',
            name='capturaTres',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='serie',
            name='capturaUno',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='serie',
            name='poster',
            field=models.CharField(max_length=150),
        ),
    ]
